### ISSUE TITLE
Resource Library's image pane allows too much vertical scrolling

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#1157]
**Describe the bug**
The scrollbar in the Resource Library is allowing too much blank space at the bottom.

**To Reproduce**
1. Visit a resource library directory that has 140+ images.
2. Scroll to the bottom.
3. Notice how the panel is empty; scrolling back up eventually reveals the bottom row of images.
4. Profit!!

**Expected behavior**
The scrollbar should not allow so much scrolling as to produce a blank panel.

**Screenshots**
Notice the amount of space below the thumb bar in the screenshot, below.  Yet the last row of data is being displayed.
![Screen Shot 2020-01-19 at 4 51 10 PM](https://user-images.githubusercontent.com/4120974/72689191-e5bff480-3adc-11ea-95d3-62c2f7a391ae.png)

**MapTool Info**
- Version: 1.6.0-alpha-4
- Install: New

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.14 (Mojave)

**Additional context**
I tested this with a directory containing 143 images.  At first, the scrollbar that appears doesn't allow scrolling to the bottom of the list.  Changing the slider to adjust the image size causes the scrollbar to recalculate its bounds, and now it allows the scrollbar to go too far.  In addition, the larger the scale factor, the more blank space at the bottom of the Image Pane.  For example, with three images across (as shown in the screen shot) there are 7 "pages" of blank space, but after scaling the images so there are only two across, there are now 10 "pages" at the bottom.  (The term "page" is measured by placing the mouse into the scrollbar area — but above or below the thumb bar — and left-clicking.  It advances by a "page" instead of by a "line".)

**Comment by Phergus** [comment]
On Windows it's the complete opposite.  You can't scroll far enough even playing with the size slider.
See #755

**Comment by aliasmask** [comment]
Maybe it has something to do with zoom slider?

**Comment by aliasmask** [comment]
I ran in to it cutting off the images at the bottom the other day (no scroll bar). Adjusting pane to recalculate usually fixes it for me.

**Comment by aliasmask** [comment]
![zoom slider example](https://user-images.githubusercontent.com/43827071/72691711-54e91900-3adc-11ea-8201-e62522cfb0db.jpg)

The only thing I changed was the zoom slider. Sometimes it cuts off bottom and sometimes it puts extra space.

**Comment by Phergus** [comment]
I usually have to adjust the panel size.  Changing the zoom slider often makes it worse.

**Comment by JamzTheMan** [comment]
This happened after @pnichols04 did some refactoring of that panel IIRC 

And yes, for Windows, things get cut off for me as well.

**Comment by Phergus** [comment]
Yup.  It didn't happen under 1.5.0.  Probably some hard-coded size calculation that assumed the font size for the labels.

**Comment by Phergus** [comment]
The issue with it cutting off the bottom row was fixed by PR #2301 in 1.8.0.  At higher zoom levels it can have too much space at the bottom but not to the same degree.

Closing this for now as resolved.

**Comment by aliasmask** [comment]
1.8.5
![not fixed bug](https://user-images.githubusercontent.com/43827071/122120406-39706380-cddf-11eb-84a6-2b39845af415.jpg)
