### ISSUE TITLE
Frame option "title" breaks frame()

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#587]
**Describe the bug**
If you use frame() with the title option, it becomes impossible to create new frames.

**To Reproduce**
1. Type:

`[frame("Frame Test", "title=mytitle"): {test}]`

2. Close the frame.

3. Try to open up the frame again

`[frame("Frame Test"): {test}]`

The second frame never comes up.

EDIT: The bug only happens if the frame "Frame Test" has never been created before.

**Expected behavior**
The command frame() continues to work after being called with the title option.

**MapTool Info**
- Version: 1.5.3
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Merudo** [comment]
Solved by my commit c1c7ab19db47a508b15f0993ba063641e51469ea

**Comment by Phergus** [comment]
This behavior was documented on the Wiki for the [frame roll option](http://www.lmwcs.com/rptools/wiki/frame_(roll_option)).  The resetFrame() macro function would reshow the frame but did not fix the problem.  Wiki needs to be updated now.

**Comment by Merudo** [comment]
Are you talking about the following sentences?

> It appears there may be a bug related macros on a library token that open a frame. Calls to the macro after closing the frame may not show the frame.

It does sound like the bug I described, but I'm not 100% sure it is (the problem was with the title statement, not with using library tokens).

**Comment by Phergus** [comment]
Yeah, the description is a bit odd. I don't really know what the first sentence means.  Probably just needs to be noted as "Prior to 1.5.4..."
